[SleepTimerEdit] small updates
 ̶-̶d̶i̶s̶a̶b̶l̶e̶ ̶p̶o̶w̶e̶r̶ ̶o̶n̶/̶o̶f̶f̶ ̶w̶h̶e̶n̶ ̶n̶o̶t̶ ̶a̶c̶t̶i̶v̶e̶ ̶a̶n̶y̶ ̶d̶a̶y̶
-check infobar instance
-sleeptimer iptv service use as dvb service
File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 3585, in
setSleepTimer
OverflowError: Python int too large to convert to C long

Co-Authored-By: Dimitrij <Dima-73@inbox.lv>