SkinSelector.py: Element in tuple must be integer, not float
Needed for Python 3.10.x

Sooner or later OE-core will update to Python 3.10.x.
No problem to apply patch now.

Fix for crash:

File "/usr/lib/enigma2/python/Screens/Screen.py", line 271, in createGUIScreen
    f()
  File "/usr/lib/enigma2/python/Screens/SkinSelector.py", line 90, in layoutFinished
    self.picload.setPara((self["preview"].instance.size().width(), self["preview"].instance.size().height(), 1.0, 1, 1, 1, "#ff000000"))
SystemError: <built-in function ePicLoad_setPara> returned a result with an exception set