[grc.cpp] Move variable 'blub' to commented out code
Variable 'blub' is used in commented out code only.
So move declaration and increment to commented out code.

Fix build with GCC-16.

 ../../sources/enigma2-3.14+git/lib/gdi/grc.cpp: In member function 'virtual void gDC::incrementSpinner()':
| ../../sources/enigma2-3.14+git/lib/gdi/grc.cpp:1123:20: error: variable 'blub' set but not used
 [-Werror=unused-but-set-variable=]
|  1123 |         static int blub;
|       |                    ^~~~