Wlan.py: Decode line to unicode
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/Console.py", line 48, in finishedCB
    callback(data, retval, self.extra_args)
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/WirelessLan/Wlan.py", line 377, in iwconfigFinished
    if "ESSID" in line:
TypeError: a bytes-like object is required, not 'str'
[ePyObject] (CallObject(<traceback object at 0xb199e048>,(0,)) failed)